name: propertylistserialization
description: iOS compatible plist serialization and deserialization library for Dart.
version: 1.1.0
homepage: https://github.com/electricbolt/dartpropertylistserialization

environment:
  sdk: '>=2.0.0 <2.12.0'

dependencies:
  convert: ^2.1.1
  xml: ^4.5.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
